### ISSUE TITLE
collection.chatbox is undefined in collection.chatbox

### ISSUE THREAD

**Issue by laszlovl** [conversejs/converse.js#1691]
Don't really understand what's going on, but this error is triggering frequently and it causes Converse to bork ("removing strophe handlers because of uncaught exception"). A timing issue?

```diff
diff --git a/src/headless/converse-muc.js b/src/headless/converse-muc.js
index 560db50..adcc4d7 100644
--- a/src/headless/converse-muc.js
+++ b/src/headless/converse-muc.js
@@ -279,7 +279,12 @@ converse.plugins.add('converse-muc', {
                 if (occupant.get('nick') === Strophe.getResourceFromJid(this.get('from'))) {
                     this.occupant = occupant;
                     this.occupant.on('destroy', this.onOccupantRemoved, this);
+
                     const chatbox = _.get(this, 'collection.chatbox');
+                    if (chatbox === undefined) {
+                        console.error("Could not find reference to this.collection.chatbox", this);
+                        return;
+                    }
```

```
Could not find reference to this.collection.chatbox 
Object { cid: "c235", attributes: {…}, _changing: false, _previousAttributes: {}, changed: {}, id: "62d4005f-ba93-4cf1-b90c-8521b806766e", _pending: false, occupant: {…}, vcard: {…}, _events: {…} }
converse-muc.js:285:32
    onOccupantAdded converse-muc.js:285
    Backbone 12
    updateOccupantsOnPresence converse-muc.js:1306
    onPresence converse-muc.js:1762
    presence_handler converse-muc.js:510
    run core.js:1308
    _dataRecv core.js:2549
    forEachChild core.js:306
    _dataRecv core.js:2538
    _onMessage websocket.js:499
```

**Comment by jcbrand** [comment]
@laszlovl I think this happens when the message gets removed but that particular event handler doesn't get deregistered. I've committed a fix. Can you please remove any patches related to this that you applied and then check whether it's fixed now?

**Comment by laszlovl** [comment]
Still seeing some of those, though since the error is caught now it doesn't seem to be problematic anymore.

```
ERROR: Could not get collection.chatbox for message: {"msgid":"blb78quohstgsanlvdo0","time":"2019-08-16T09:16:27.881Z","ephemeral":false,"chat_state":0,"is_archived":true,"is_delayed":true,"is_spoiler":false,"message":"message","references":[],"type":"groupchat","stanza_id jid@jid.com":"1565946987881391","from":"jid@jid.com/resource","nick":"Nick","sender":"them","received":"2019-09-16T10:54:10.559Z","id":"c759f12c-f6b7-472f-bc19-b346f22caa12","vcard_jid":"jid@jid.com"}
```

It looks quite reproducable in my setup, it concerns the same couple of MUC messages every time. First time logging in (with an empty localstorage) there are no errors, but if I close the Converse tab then re-open it there they are.

The affected messages do show in the MUC normally.

**Comment by jcbrand** [comment]
I also still sometimes see these errors but I haven't been able yet to drill down and find the underlying cause.
