### ISSUE TITLE
Automatic reconnects of anonymous users do not re-autojoin MUCs

### ISSUE THREAD

**Issue by VShell** [conversejs/converse.js#2206]
**Describe the bug**

When an anonymous user gets automatically reconnected, [clearSession gets called](https://github.com/conversejs/converse.js/blob/823134d7629bad2b82875964169340609c0ce2c9/src/headless/converse-core.js#L359). The result of this is that [all chat rooms are closed](https://github.com/conversejs/converse.js/blob/823134d7629bad2b82875964169340609c0ce2c9/src/converse-chatboxviews.js#L149). Autojoining the rooms then doesn't happen, as this depends on [the chatBoxesFetched event](https://github.com/conversejs/converse.js/blob/6590a0cf7b8ee04118a04491e30f66925701643f/src/headless/converse-muc.js#L2333), which [is not triggered on reconnect](https://github.com/conversejs/converse.js/blob/b0cb4897691a06c86e471e2e76b72266311cb5fd/src/headless/converse-chatboxes.js#L84).

**To Reproduce**
1. Be using 6.0.1
2. Initialize Converse.JS against a functioning server with authentication: anonymous, auto_login: true, and at least one auto_join_rooms
3. Using Firefox's debugger, pause execution for upwards of 60 seconds - or otherwise somehow force a reconnect
4. The MUC will be gone

**Expected behavior**
I would expect that auto_join_rooms will function on every connection, not just the first one on the page.

**Environment (please complete the following information):**
 - Desktop or Mobile? Desktop
 - Browser [e.g. Chrome, Firefox] Firefox
 - Converse.js version [e.g. 4.2.0] 6.0.1

**Comment by jcbrand** [comment]
@VShell Thanks for the bug report. Could you please check whether this also happens with the tip of the master branch?

I think this might have been fixed already.

**Comment by VShell** [comment]
@jcbrand Unfortunately not fixed, and this one additionally seems to get caught up in an authentication failure loop once it's disconnected once.
