### ISSUE TITLE
Troubleshooting OMEMO

### ISSUE THREAD

**Issue by ZenithElevate** [conversejs/converse.js#3769]
When I uncomment the line

`<!--script src="libsignal-protocol.js"></script-->`

the ConverseJS side stops getting messages and instead sees this error:

`I sent you an OMEMO encrypted message but your client doesn’t seem to support that. Find more information on https://conversations.im/omemo`

If the user switches to Gajim or Pidgin, then messages pass successfully, in both directions.
The other side is Android Conversation.
How can we troubleshoot this and fix?

**Comment by jcbrand** [comment]
OMEMO does work, I and many other people use it every day, so there's likely something wrong on your end.

To help troubleshoot, please verify that when you uncomment the `libsignal-protocol.js` line, the browser actually loads that script.

1. Open your browser’s developer tools (usually F12 or right-click → Inspect).
2. In the **Network** tab, reload the page and look for **libsignal-protocol.js**. Ensure it returns a **200** status and is not blocked by CORS or missing.
3. In the **Console** tab, check for any loading or parsing errors related to **libsignal-protocol.js**. If the file fails to load, you’ll see an error message there.
4. In the Console prompt, type `typeof libsignal` or `window.libsignal` to confirm the library is defined.

If the file is loaded correctly and you still see the OMEMO support message:
- Make sure you include `libsignal-protocol.js` **before** loading `converse.js`
- Enable converse.js debug logging by appending `#converse?loglevel=debug` to your URL or setting `loglevel: 'debug'` in your `converse.initialize()` options. Then watch for errors or OMEMO-related log entries.
- Try isolating the test in a minimal HTML page (only `libsignal-protocol.js`, `converse.js`, and basic config) to rule out conflicts with other plugins or scripts.
- Clear your browser cache or do a hard reload (Ctrl+Shift+R) to ensure you’re loading the latest files.

**Comment by ZenithElevate** [comment]
The page was indeed loading libsignal after converse. I swapped the lines, but the error persists, and we are only able to exchange messages when Android Conversation disables OMEMO.

```
<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" type="text/css" media="screen" href="converse.min.css">
<script src="libsignal-protocol.js"></script>
<script src="converse.min.js" charset="utf-8"></script>
</head>
<body>

<script>
    converse.initialize({
        bosh_service_url: 'https://xmpp.mydomain.local:7443/http-bind/',
        view_mode: 'fullscreen',
        allow_non_roster_messaging: true,
        allow_registration: false,
        default_domain: 'xmpp.mydomain.local',
        discover_connection_methods: false,
        message_archiving: 'never',
        omemo_default: false,
    });
</script>
</body>
</html>
```

In the network, libsignal is 200.
In the console, there are no errors. These are the only lines that are not white background:

```
asm.js type error: Asm.js optimizer disabled because debugger is active libsignal-protocol.js
 2025-07-30T11:04:02.989Z WARNING: Not pinging when we know we're not authenticated <empty string> log.js:68:19
downloadable font: glyf: empty gid 3 used as component in glyph 98 (font-family: "Baumans" style:normal weight:400 stretch:100 src index:2) source: https://www.myhosting.local/path_to_converse/webfonts/baumans.ttf
```
With debug enabled, I see the same errors as in the chat window, to the effect that this client does not support OMEMO.

I prefer the title of this case to stay the way I'd created it, for the tracking on my side. You should be able to edit it however you like, once this is resolved. Thanks for the understanding.

**Comment by jcbrand** [comment]
Sounds to me like the problem is not that OMEMO isn't working, but that the messages that are being sent to you are not encrypted for your device (i.e. that instance of Converse).

The other client(s) you're chatting with need to fetch the device list from PubSub and then use the info for each device in the list to encrypt the message for that device.

Either your instance of Converse does not have its info in the device list, or the other client has a stale device list which needs to be updated.

Try using Converse with OMEMO in the browser's incognito mode, or in a different browser, or try deleting all local content (including IndexedDB) in your current browser, so that a new device bundle is created and uploaded and then try sending and receiving encrypted messages.

Concerning the title, you can make a bookmark of this page to keep track of this issue.

**Comment by ZenithElevate** [comment]
Could you change the programming of ConverseJS so that it more resembles desktop IM clients in which users don't have to take manual care of OMEMO, and it works automatically OOB?
I will not be able to babysit each and every member who switches over to ConverseJS and immediately comes to me with this problem? Because it occurs on the 1st transition, for everyone, and the rejection is mounting, across the member base.
I also will not be able to dictate to mobile device users what they have to do to communicate with our members, for obvious reasons. They will simply stop if they have to use manual workarounds.
Bottom line is, OMEMO does not work, however you slice and dice it.

**Comment by kicken** [comment]
I don't usually bother with encryption, but the couple times I have tried testing with it while working on the desktop app I've had issues with it between ConverseJS and Conversations on android.   I just tried again and found it to not work well.  Here's a summary of what I did.

1.  Opened chat.conversejs.org in a tab, cleared all the site data in dev tools then reloaded.
2. Logged into my test account, which has my main account already added in the roster.
3. My main account is signed in on my phone using Conversations.
4. When opening a chat with my main account, the encryption icon is initially disabled, converse says the account does not support encryption.
5. Sending an encrypted message from conversations arrives properly and the encryption icon becomes available in converse.
6. I enable encryption in converse.js and attempt to send a reply back to my main account
7. The reply fails to send and the following is logged in the developer tools

```
 ERROR: Could not fetch bundle for device 3586 from alice@aoeex.com <anonymous code>:1:147461
 ERROR: <iq xmlns="jabber:client" type="error" id="3668e181-1d5a-4222-b34a-2e020e240d3e:sendIQ" from="alice@aoeex.com" to="alice@aoeex.com/converse.js-70851826"><pubsub xmlns="http://jabber.org/protocol/pubsub"><items node="eu.siacs.conversations.axolotl.bundles:3586"/></pubsub><error code="404" type="cancel"><item-not-found xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error></iq> <anonymous code>:1:147461
 ERROR: Could not build an OMEMO session for device 3586 because we don't have its bundle <anonymous code>:1:147461
 ERROR: encrypt/</<@https://cdn.conversejs.org/3rdparty/libsignal-protocol.min.js:1:881814
promise callback*encrypt/<@https://cdn.conversejs.org/3rdparty/libsignal-protocol.min.js:1:881701
promise callback*queueJobForNumber@https://cdn.conversejs.org/3rdparty/libsignal-protocol.min.js:1:894316
encrypt@https://cdn.conversejs.org/3rdparty/libsignal-protocol.min.js:1:881287
560/LU/</l</<@https://chat.conversejs.org/dist/converse.min.js:307:14652
560/LU/</l<@https://chat.conversejs.org/dist/converse.min.js:307:14697
560/LU/<@https://chat.conversejs.org/dist/converse.min.js:307:14594
KL@https://chat.conversejs.org/dist/converse.min.js:307:586
o@https://chat.conversejs.org/dist/converse.min.js:307:792
promise callback*KL@https://chat.conversejs.org/dist/converse.min.js:307:657
o@https://chat.conversejs.org/dist/converse.min.js:307:792
promise callback*KL@https://chat.conversejs.org/dist/converse.min.js:307:657
o@https://chat.conversejs.org/dist/converse.min.js:307:792
560/JL/</<@https://chat.conversejs.org/dist/converse.min.js:307:852
560/JL/<@https://chat.conversejs.org/dist/converse.min.js:307:730
LU@https://chat.conversejs.org/dist/converse.min.js:314:192
n@https://chat.conversejs.org/dist/converse.min.js:328:5424
eF@https://chat.conversejs.org/dist/converse.min.js:328:4029
o@https://chat.conversejs.org/dist/converse.min.js:328:6342
560/initialize/</</<@https://chat.conversejs.org/dist/converse.min.js:328:6402
560/initialize/</<@https://chat.conversejs.org/dist/converse.min.js:328:6280
560/initialize/<@https://chat.conversejs.org/dist/converse.min.js:328:6415
560/hook/</<@https://chat.conversejs.org/dist/converse.min.js:2:94934
promise callback*560/hook/<@https://chat.conversejs.org/dist/converse.min.js:2:94923
hook@https://chat.conversejs.org/dist/converse.min.js:2:94906
560/og/createMessageStanza/<@https://chat.conversejs.org/dist/converse.min.js:56:45
<anonymous code>:1:147461
Uncaught (in promise) Error: No record for alice@aoeex.com.3586
    encrypt libsignal-protocol.min.js:1
    promise callback*encrypt/< libsignal-protocol.min.js:1
    promise callback*queueJobForNumber libsignal-protocol.min.js:1
    encrypt libsignal-protocol.min.js:1
    l utils.js:998
    l utils.js:1028
    LU utils.js:1028
    KL utils.js:7
    o utils.js:7
    promise callback*KL utils.js:7
    o utils.js:7
    promise callback*KL utils.js:7
    o utils.js:7
    JL utils.js:7
    JL utils.js:7
    LU utils.js:1059
    n index.js:82
    eF index.js:6
    o index.js:87
    initialize index.js:87
    initialize index.js:87
    initialize index.js:87
    hook events.js:60
    promise callback*560/hook/< events.js:60
    hook events.js:60
    createMessageStanza model-with-messages.js:976
libsignal-protocol.min.js:1:881814
```

Looking in the Openfire Admin Console, the requested bundle does indeed not exist. I'm not sure why it is being searched for, or what the consequences would be if converse.js simply ignored the fact that it doesn't exist vs returning an error.

**Comment by ZenithElevate** [comment]
@kicken If it helps you, switching to incognito windows for ConverseJS seems to work. It likely starts from a clean slate, w/o any fingerprints, and the exchange occurs, which Android Conversation confirms visually. In normal browser window, there is no fingerprint exchange. I am not even going to attempt cleaning the browser DBs because it's preposterous to require that from each of many members.

**Comment by jcbrand** [comment]
>  I am not even going to attempt cleaning the browser DBs because it's preposterous to require that from each of many members.

@ZenithElevate I was proposing cleaning the DB in order to diagnose the problem, not that you should expect this from your users.

In your first post you wrote: `How can we troubleshoot this and fix?`

Well that's one way you can troubleshoot.

@kicken: Just to recap, you're trying to reply and then get the message:
```
ERROR: Could not build an OMEMO session for device 3586 because we don't have its bundle
```
And then you confirmed that the bundle doesn't exist.

>  I'm not sure why it is being searched for, or what the consequences would be if converse.js simply ignored the fact that it doesn't exist vs returning an error.

Converse needs the bundle in order to establish a shared encryption key between itself and the Conversations device.
If it's not available, then either your Conversations device hasn't published its bundle (as it should) or some other device has removed that bundle (which would be a bug).

But generally speaking, Converse is not responsible for your Conversations device uploading its bundle and this might be a Conversations bug (although I'm of course not ruling out an issue in Converse).

Perhaps @iNPUTmice has an idea what might be going on here.

**Comment by kicken** [comment]
@jcbrand I know converse.js would need the bundle to encrypt the message for that device, but it seems like that one device being missing shouldn't be preventing the message from being sent.  I have no idea what device that would be, or if it's even valid anymore.  Likely it was some previous instance of Converse.js I tested with at some point. 

I took a look at the code, and it looks like there was an attempt to handle this, but it's not currently working.  [This commit](https://github.com/kicken/converse.js/commit/aa6a261f02ba74ea910c3503f315d82ece7c066f) appears to fix this specific issue in my  limited testing.  With the change applied, I can successfully send an encrypted message despite the unknown device.

There are still a few other things that I think probably need some work to make the user experience better, but since I don't typically use encryption and haven't read up on it I don't know if there are technical limitations in the way or not.

I did some additional testing using Converse Desktop, clearing out the data folder each time so it's a completely fresh "device".  

1.  When I first connect, Converse.js thinks my contact is not OMEMO capable until I first receive an encrypted message from them.  Clicking the OMEMO tab in the contacts profile shows no fingerprints.  Once I send an encrypted message from them to Converse.js, it then has the devices fingerprint and can encrypt.   If Conversations can send an encrypted first message to a devices, it seems like Converse.js should be able to do so as well.

2. If I have my account open in both Conversations and Converse.js at the same time, messages sent with one are unreadable by the other.  It seems neither client is able to encrypt the message in a way that it's readable by my own other devices.  Is that expected?  
 
3. There was at least one instance where trying to send the encrypted message to Converse.js after a fresh launch "failed" because the message was not encrypted for that device, I guess Conversations didn't pick up the new devices finger print.  I'm currently unable to reproduce that again though at the moment.

**Comment by kicken** [comment]
I did some more troubleshooting of my OMEMO issues and found some things that I believe are bugs, and a couple other things I am unsure about.  I can file these as separate issues with more details if desired for tracking purposes, but I will summarize my findings here as well.

1. **Converse fails to recognize new OMEMO devices.** Adding a new device to your device list is not picked up by converse.  This seems to be due to Converse not requesting the device list after the first use.  Subsequent runs use a cached copy I think.  As a result, messages sent do not get encrypted for that new device and are unreadable.
2. **Converse does not process new device list updates.**  Converse is not properly processing notifications when a device list is updated. This seems to be due to converse looking for a message with type="headline" but that type isn't always set. As a result, messages sent do not get encrypted for that new device and are unreadable.
3. **Converse cannot update the device list sometimes.**  This is less of a bug and more an edge case that I'm not sure if a workaround can be added or not.  Part of the issue I was having is that my primary account's device list node was created with the access mode set to presense.  I think this is a result of it being created before Openfire supported node configuration but I am unsure.  The result is that whenver converse tried to add itself to the device list it would fail with a conflict/precondition-not-met error.  Would it be possible to detect this and attempt changing the access mode or deleting and re-creating the node?

**Comment by ZenithElevate** [comment]
I get this even when both users are on ConverseJS, and their locks are locked:

<img width="453" height="73" alt="Image" src="https://github.com/user-attachments/assets/3f25a612-716e-4d03-b7c3-edcecd978a56" />

<img width="504" height="47" alt="Image" src="https://github.com/user-attachments/assets/217c46a6-4982-49fd-8362-bd43744649f9" />

There are neither errors nor warnings in the console.
Could you do more testing of different scenarios?

**Comment by dca00** [comment]
Not sure if this helps you folks, but before we backed out of our pilot deployment of this web client, we had to disable encryption across the board because it did not work reliably between any combination of any clients. We were getting random errors like above. It works for a while, but then something goes out of sync, and the same errors begin to rain. Something triggers error condition, and this web client is not able to recover, so we had no choice but pull it. Even though Windows clients are retarded, they still work reliably when this web client cannot.

I am under impression that part of the issue is that existing accounts do not survive when their users switch from Windows apps to web. Maybe their tokens have to be wiped out on both sides before the switchover, but the effort was going to be enormous (50+k accounts) and no one was going to take this on.

Good part of this web client is that it is enough to unlock the encrypt button, and messages begin to pass. In desktop clients, we had to disable lurch on both sides. This probably has to do with the fact that this web client has no 'require' setting that Windows clients have and which we set to on at all times.

Just my 2c. I'll be happy to revisit and test encryption if it improved since  we erased this from our web server.

**Comment by jcbrand** [comment]
> Converse does not process new device list updates. Converse is not properly processing notifications when a device list is updated. This seems to be due to converse looking for a message with type="headline" but that type isn't always set. As a result, messages sent do not get encrypted for that new device and are unreadable.

I've pushed a fix for this to the branch I'm currently working in. https://github.com/conversejs/converse.js/commit/8c01b09b3bc67b0a75b8b36554a7adc94b28edba

**Comment by kicken** [comment]
I've re-tested the scenarios I originally found with the latest master branch.

> 1. **Converse fails to recognize new OMEMO devices.** 
> 2. **Converse does not process new device list updates.**  

These issues appear to be fixed.  I was unable to re-produce these problems.

> 3. **Converse cannot update the device list sometimes.**  

This issue remains, and appears to be a result of #3791.

**Comment by kicken** [comment]
After fixing #3791 & #3792, converse.js is able to successfully publish the new device list, but not by re-configuring the node.  The reconfiguration still fails, and the fallback of publishing the node without the access_model pre-condition is what succeeds.

Debugging this, the cause seems to be the configuration containing the pubsub#collection element. This might just be an Openfire issue, not sure.  Openfire rejects the new configuration with a not-acceptable error (debugging shows extended info "Specified node in field pubsub#collection [] does not exist").

I tried modifying converse.js to not download the current config and just set the access model and that appears to work fine.  Not sure if that would be an appropriate fix or if that would cause other issues elsewhere.

**Comment by Neustradamus** [comment]
@ZenithElevate, @kicken, @dca00: Thanks for your diagnostic about OMEMO and @jcbrand for this work about this.

**Comment by jcbrand** [comment]
Thank you @kicken, great job finding and reporting these bugs!

Issues spun out of this one:

- #3791
- #3792

**Comment by zeghuno** [comment]
> [@ZenithElevate](https://github.com/ZenithElevate), [@kicken](https://github.com/kicken), [@dca00](https://github.com/dca00): Thanks for your diagnostic about OMEMO and [@jcbrand](https://github.com/jcbrand) for this work about this.

This was a strange way to thank us for that:

<img width="559" height="497" alt="Image" src="https://github.com/user-attachments/assets/4d168f6b-8db3-46a2-8dc6-0a99d7701d8e" />

**Comment by jcbrand** [comment]
@zeghuno I blocked you because you thought it was a good idea to get into a power struggle with me regarding the name of this issue and because you were acting entitled and generally being annoying with your negative emotive language (like calling my suggestion for troubleshooting the issue "preposterous").

One would think it's common sense that if you're asking other people to spend their free time to help you with something, even to the extent that they need to do unpaid work for you, that you would in the least make an effort to be polite and respectful and to also reciprocate from your side by making an effort to provide actionable information and to implement suggestions to troubleshoot the issue.

But for a sizable minority of people, like yourself, this is apparently not common sense.

@kicken is the one here who came up with actionable information and who provided two fixes. I also spent my time to find bugs and make fixes. Have you thought about thanking us?

You could have written here to thank us and apologize and ask to be unblocked, but you're too entitled, thinking that we somehow owe you something.

To the extent that you created an issue (without using the bug report template and thereby omitting lots of relevant info) and thereby instigated the effort to have these issues fixed, I'm grateful, but that's a small part of what was done here.

If you're willing to apologize I'll remove the block and we can continue in good faith without any hard feelings. If not, then that's also fine with me.

**Comment by zeghuno** [comment]
Everything is the other way around.
Hadn't we come here, none of this would have been noticed or fixed.
You took the issue personally, became defensive, circled the wagons and repeatedly vandalized our issue.
In the end, you had to acknowledge that yes, OMEMO does not work, and that it requires not one, but 3 bugfixes to fix.
And now you dig yourself deeper by staying in denial and coming up with more personal insults.
We are not developers. We are not able to do debugging. We are users, and we only notice things that do not work.
It is sad that you disgrace yourself so persistently.

> [@zeghuno](https://github.com/zeghuno) I blocked you because you thought it was a good idea to get into a power struggle with me regarding the name of this issue and because you were acting entitled and generally being annoying with your negative emotive language (like calling my suggestion for troubleshooting the issue "preposterous").
> 
> One would think it's common sense that if you're asking other people to spend their free time to help you with something, even to the extent that they need to do unpaid work for you, that you would in the least make an effort to be polite and respectful and to also reciprocate from your side by making an effort to provide actionable information and to implement suggestions to troubleshoot the issue.
> 
> But for a sizable minority of people, like yourself, this is apparently not common sense.
> 
> [@kicken](https://github.com/kicken) is the one here who came up with actionable information and who provided two fixes. I also spent my time to find bugs and make fixes. Have you thought about thanking us?
> 
> You could have written here to thank us and apologize and ask to be unblocked, but you're too entitled, thinking that we somehow owe you something.
> 
> To the extent that you created an issue (without using the bug report template and thereby omitting lots of relevant info) and thereby instigated the effort to have these issues fixed, I'm grateful, but that's a small part of what was done here.
> 
> If you're willing to apologize I'll remove the block and we can continue in good faith without any hard feelings. If not, then that's also fine with me.

**Comment by jcbrand** [comment]
> Hadn't we come here, none of this would have been noticed or fixed.

Actually, had Kicken and I not sit down and do the work, nothing would have been fixed. Anyone can create a ticket, not anyone can actually do the work to fix the bugs. The correct response to have when people are helping you with something difficult that you can't do yourself is to show gratitude.

> You took the issue personally, became defensive, circled the wagons and repeatedly vandalized our issue.

I'll admit that I have a pet peeve when people write lazy issues (by avoiding the bug report template) where they just state that "X doesn't work", especially when X is something that I use every day.

That said, it's not your issue just as it's not your issue tracker. Your ability to create issues here is a privilege, not a right.

> In the end, you had to acknowledge that yes, OMEMO does not work, and that it requires not one, but 3 bugfixes to fix.

I and many other people use Converse with OMEMO every day. In some instances, for example with Openfire, which apparently doesn't use `headline` for PEP messages (Prosody and EJabberd both do), it didn't work, but that's not the same as saying it doesn't work at all.

Here are your own words: "switching to incognito windows for ConverseJS seems to work"

So, there are scenarios where it works and ones where it doesn't work, and the shared goal should be to figure out under which scenarios it doesn't work.
