### ISSUE TITLE
Stale status in roster after resume from sleep

### ISSUE THREAD

**Issue by dca00** [conversejs/converse.js#3804]
**Describe the bug**
After the app restores connection after resume from sleep, roster statuses may not update since when the system had been put in standby mode.

**To Reproduce**
1. Sleep the system
2. Resume
3. Wait until the spinning dots finish and the roster reloads
4. Check the peer statuses. Some statuses will be stale

**Expected behavior**
Statuses should be actual.

**Screenshots**

**Environment (please complete the following information):**
 - Desktop
 - Browser Firefox
 - Converse.js version 10.1.8 and 11.0.1

**Additional context**

Log out and back in to see the updated statuses; some will be different then after connection auto-restore

**Comment by jcbrand** [comment]
Closing. Should be fixed as part of #3802

**Comment by dca00** [comment]
Still an issue in v. 12
Just wondering whether any testing was done or only the ticket was closed?

**Comment by jcbrand** [comment]
This ticket is closed as a duplicate of #3802, which is still open.
